name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Create hello.txt file
        run: echo "Hello, world!" > hello.txt
          
      - name: SSH into Azure server and run commands
        run: |
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker rm $(sudo docker ps -a -q)
          sudo docker rmi $(sudo docker images -a -q)
          echo "Executing commands on Azure server..."  # Echo to indicate script execution
          ssh -o StrictHostKeyChecking=no azureuser@4.233.208.158 'sudo docker-compose -f /home/azureuser/shopping-mongodb-docker/docker-compose.yaml up -d'
          echo "Script execution completed on Azure server."  # Echo after script execution
